services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${mypassword}
      MYSQL_DATABASE: TaipeiDayTrip
      MYSQL_USER: root
      MYSQL_PASSWORD: ${mypassword}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      mypassword: ${mypassword}
      mykey: ${mykey}
      partner_key: ${partner_key}
      MYSQL_HOST: db
      MYSQL_DATABASE: TaipeiDayTrip
      MYSQL_USER: root
      MYSQL_PASSWORD: ${mypassword}
    networks:
      - backend


volumes:
  db_data:

networks:
  backend: